# Generated by Django 6.0.5 on 2026-05-20 18:54

import agency.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Информация о компании (просто текст)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Логотип (***)')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на видео (***)')),
                ('history_by_years', models.TextField(blank=True, null=True, verbose_name='История по годам (***)')),
                ('requisites', models.TextField(blank=True, null=True, verbose_name='Реквизиты (***)')),
            ],
            options={
                'verbose_name': 'О компании',
                'verbose_name_plural': 'О компании',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название страны')),
                ('climate_winter', models.CharField(max_length=150, verbose_name='Климат зимой')),
                ('climate_spring', models.CharField(max_length=150, verbose_name='Климат весной')),
                ('climate_summer', models.CharField(max_length=150, verbose_name='Климат летом')),
                ('climate_autumn', models.CharField(max_length=150, verbose_name='Климат осенью')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250, verbose_name='Вопрос / Термин')),
                ('answer', models.TextField(verbose_name='Ответ / Определение')),
                ('date_added', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Термин/Вопрос',
                'verbose_name_plural': 'Словарь терминов и понятий',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('short_description', models.CharField(max_length=250, verbose_name='Краткое содержание (одно предложение)')),
                ('content', models.TextField(verbose_name='Полное содержание статьи')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='Картинка')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Промокод')),
                ('discount_amount', models.IntegerField(verbose_name='Размер скидки (в %)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действующий (иначе в архиве)')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды и купоны',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название вакансии')),
                ('description', models.TextField(verbose_name='Описание вакансии')),
                ('salary', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заработная плата')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть в формате: +375 (29) XXX-XX-XX. Допустимые коды: 25, 29, 33, 44.', regex='^\\+375 \\((25|29|33|44)\\) \\d{3}-\\d{2}-\\d{2}$')], verbose_name='Телефон')),
                ('birth_date', models.DateField(null=True, validators=[agency.models.validate_adult], verbose_name='Дата рождения (18+)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт Django')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО сотрудника')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть в формате: +375 (29) XXX-XX-XX. Допустимые коды: 25, 29, 33, 44.', regex='^\\+375 \\((25|29|33|44)\\) \\d{3}-\\d{2}-\\d{2}$')], verbose_name='Телефон')),
                ('birth_date', models.DateField(null=True, validators=[agency.models.validate_adult], verbose_name='Дата рождения (18+)')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employees/', verbose_name='Фото сотрудника')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт Django')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название отеля')),
                ('stars', models.IntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], verbose_name='Количество звезд')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость в сутки')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта для карты (***)')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота для карты (***)')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='agency.country', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Отель',
                'verbose_name_plural': 'Отели',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='Имя автора (если не зарегистрирован)')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Оценка')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название путевки/направления')),
                ('duration_weeks', models.IntegerField(choices=[(1, '1 неделя'), (2, '2 недели'), (4, '4 недели')], verbose_name='Длительность (в неделях)')),
                ('departure_date', models.DateField(verbose_name='Дата отправления')),
                ('is_hot', models.BooleanField(default=False, verbose_name='Горящая путевка')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='agency.hotel', verbose_name='Отель')),
            ],
            options={
                'verbose_name': 'Путевка',
                'verbose_name_plural': 'Путевки',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата оформления заказа')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Итоговая стоимость')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='agency.client', verbose_name='Клиент')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_handled', to='agency.employee', verbose_name='Сотрудник, оформивший заказ')),
                ('tours', models.ManyToManyField(related_name='orders', to='agency.tour', verbose_name='Выбранные путевки')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
